"""Regenerate the bundled romanization table from a pinned Mozc revision."""
import hashlib
import json
from pathlib import Path
from urllib.request import urlopen

REVISION = 'b9c3fcbd6d76b19649ef572324fa9da2559bc18e'
URL = f'https://raw.githubusercontent.com/google/mozc/{REVISION}/src/data/preedit/romanji-hiragana.tsv'
ROOT = Path(__file__).resolve().parents[1]

def main():
    data = urlopen(URL, timeout=30).read(65537)
    if len(data)>65536:
        raise ValueError('Romaji table too large')
    lines=['// Generated by scripts/import_romaji_table.py; do not edit individual mappings.',
           f'// Source: {URL}', f'// SHA-256: {hashlib.sha256(data).hexdigest()}',
           '// Copyright Google LLC. BSD-3-Clause; see third_party/public-dictionary-NOTICE.txt.']
    for line in data.decode('utf-8').splitlines():
        fields=line.split('\t')
        if len(fields)<2: continue
        key,text=fields[:2]
        pending=fields[2] if len(fields)>2 else ''
        if pending and not key.endswith(pending):
            raise ValueError('Unsupported state transition')
        values=', '.join('u8'+json.dumps(value,ensure_ascii=False) for value in (key,text,pending))
        lines.append('{'+values+'},')
    (ROOT/'native/src/romaji_table.inc').write_text('\n'.join(lines)+'\n',encoding='utf-8')
    print(f'Imported {len(lines)-4} rules')

if __name__=='__main__': main()
